// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.22.2
// source: api/au/v1/au.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAssetUnitPlaceOrder = "/au.v1.AssetUnit/PlaceOrder"
const OperationAssetUnitSayHello = "/au.v1.AssetUnit/SayHello"

type AssetUnitHTTPServer interface {
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderReply, error)
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterAssetUnitHTTPServer(s *http.Server, srv AssetUnitHTTPServer) {
	r := s.Route("/")
	r.GET("/helloworld/{name}", _AssetUnit_SayHello0_HTTP_Handler(srv))
	r.POST("/placeorder", _AssetUnit_PlaceOrder0_HTTP_Handler(srv))
}

func _AssetUnit_SayHello0_HTTP_Handler(srv AssetUnitHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetUnitSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

func _AssetUnit_PlaceOrder0_HTTP_Handler(srv AssetUnitHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlaceOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetUnitPlaceOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PlaceOrder(ctx, req.(*PlaceOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlaceOrderReply)
		return ctx.Result(200, reply)
	}
}

type AssetUnitHTTPClient interface {
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest, opts ...http.CallOption) (rsp *PlaceOrderReply, err error)
	SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
}

type AssetUnitHTTPClientImpl struct {
	cc *http.Client
}

func NewAssetUnitHTTPClient(client *http.Client) AssetUnitHTTPClient {
	return &AssetUnitHTTPClientImpl{client}
}

func (c *AssetUnitHTTPClientImpl) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...http.CallOption) (*PlaceOrderReply, error) {
	var out PlaceOrderReply
	pattern := "/placeorder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetUnitPlaceOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AssetUnitHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAssetUnitSayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
